name: autotests

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10, 12]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci
    - run: npm run test:cov

    - name: Generate lcov report
      if: matrix.node-version == 10
      run: npx nyc report --reporter=lcov

    - name: Run coveralls
      uses: coverallsapp/github-action@master
      if: matrix.node-version == 10
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
